<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class DiaDiemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dia_diems')->insert([
            [
                'ten_dia_diem' => 'địa điểm 1',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 1',
                'noi_dung' => 'noi dung địa điểm 1',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_1.jpeg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 11 đường N11',
                'noi_bat'=>0,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 2',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 2',
                'noi_dung' => 'noi dung địa điểm 2',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_2.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 12 đường N12',
                'noi_bat'=>0,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 3',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 3',
                'noi_dung' => 'noi dung địa điểm 3',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_3.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 13 đường N13',
                'noi_bat'=>0,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 4',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 4',
                'noi_dung' => 'noi dung địa điểm 4',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_4.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 14 đường N14',
                'noi_bat'=>0,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 5',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 5',
                'noi_dung' => 'noi dung địa điểm 5',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_2.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 15 đường N15',
                'noi_bat'=>0,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 6',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 6',
                'noi_dung' => 'noi dung địa điểm 6',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_3.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 16 đường N16',
                'noi_bat'=>1,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 7',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 7',
                'noi_dung' => 'noi dung địa điểm 7',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_4.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 17 đường N17',
                'noi_bat'=>1,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 8',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 8',
                'noi_dung' => 'noi dung địa điểm 8',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_2.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 18 đường N18',
                'noi_bat'=>1,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 9',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 9',
                'noi_dung' => 'noi dung địa điểm 9',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_3.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 14 đường N14',
                'noi_bat'=>1,
                'trang_thai'=>1,
            ],
            [
                'ten_dia_diem' => 'địa điểm 10',
                'vi_do' => null,
                'sao' => null,
                'mua_du_lich' =>'Đông',
                'mo_ta' => 'mô tả địa điểm 10',
                'noi_dung' => 'noi dung địa điểm 10',
                'hinh_anh_dia_diem' => 'hinh_test/dia_danh_4.jpg',
                'tinh'=>'Đồng Nai',
                'huyen'=>'Long Thành',
                'xa'=>'Xã Bình An',
                'chi_tiet_dia_chi'=>'số 14 đường N14',
                'noi_bat'=>1,
                'trang_thai'=>1,
            ],
        ]);
    }
}
